In [38]:
"""
Author: Marco Montemore
Affiliation: Undergraduate Research Assistant & Student
Organization: University of Oregon - DSCI 410L (DSiA)
Date: 05/02/2026
Description: This program is designed to statistcally compare and visualize mobile crisis and first responder
             data in Eugene/Springfield, Oregon.
""";

In [39]:
# Import necessary libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Load the Datasets:

In [40]:
# Loading the cleaned datasets.
CAD_Data = pd.read_csv("../cleaning/Eugene_CAD_Data/CAD_CLEAN.csv")
SPD_Data = pd.read_csv("../cleaning/Springfield_SPD_Data/SPD_CLEAN.csv")
MCSLC_Data = pd.read_csv("../cleaning/MCSLC_Data/MCSLC_CLEAN.csv")

# Reading in datasets below:

In [41]:
CAD_Data

,Agency,ID,Call Time,Nature,Closed As,Seconds to Arrival,Prime Unit,Precipitation Type,Snow,Snow Depth,Conditions,Is CAHOOTS
0,EPD,15000001,2015-01-01 00:00:00,PERSON STOP,ASSISTED,0.0,_5E48,nopn,0.0,0.0,Clear,0
1,EPD,15000002,2015-01-01 00:00:44,FIGHT,RESOLVED,0.0,_3F65,nopn,0.0,0.0,Clear,0
2,EPD,15000003,2015-01-01 00:01:05,CHECK WELFARE,ASSISTED,1094.0,_3J79,nopn,0.0,0.0,Clear,1
3,EPD,15000007,2015-01-01 00:03:16,SHOTS FIRED,PATROL CHECK,576.0,_5E48,nopn,0.0,0.0,Clear,0
4,EPD,15000010,2015-01-01 00:03:34,ILLEGAL FIREWORKS,ADVISED,0.0,_5K97,nopn,0.0,0.0,Clear,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1091089,EPD,25327368,2025-12-31 23:39:12,TRAFFIC STOP,SOBRIETY CHECK,0.0,_4U41,nopn,0.0,0.0,Partially cloudy,0
1091090,EPD,25327370,2025-12-31 23:40:48,TRAFFIC STOP,UNIFORM TRAFFIC CITATION ISSUED,1.0,_5E56,nopn,0.0,0.0,Partially cloudy,0
1091091,EPD,25327374,2025-12-31 23:45:57,PATROL CHECK,UNIFORM TRAFFIC CITATION ISSUED,0.0,_4E48,nopn,0.0,0.0,Partially cloudy,0
1091092,EPD,25327376,2025-12-31 23:49:12,ASSIST OREGON STATE POLICE,ASSISTED,0.0,_5T81,nopn,0.0,0.0,Partially cloudy,0
1091093,EPD,25327378,2025-12-31 23:56:03,SUSPICIOUS CONDITIONS,PATROL CHECK,670.0,_5E56,nopn,0.0,0.0,Partially cloudy,0

In [42]:
SPD_Data

,ID,Call Time,Nature,Closed As,Seconds to Arrival,Prime Unit,Precipitation Type,Snow,Snow Depth,Conditions,Is CAHOOTS
0,15000074,2015-01-01 01:16:00,AUDIBLE ALARM,Building Check Secure,300.0,1S18,nopn,0.0,0.0,Clear,0
1,15000083,2015-01-01 01:22:00,DWS,Uniform Traffic Citation Issued,0.0,3D2,nopn,0.0,0.0,Clear,0
2,15000216,2015-01-01 05:27:00,DWS,Uniform Traffic Citation Issued,0.0,1S22,nopn,0.0,0.0,Clear,0
3,15000222,2015-01-01 05:52:00,SUSPICIOUS VEHICLE,Information Only,240.0,1S11,nopn,0.0,0.0,Clear,0
4,15000234,2015-01-01 07:49:00,AUDIBLE ALARM,Building Check Secure,480.0,2S11,nopn,0.0,0.0,Clear,0
...,...,...,...,...,...,...,...,...,...,...,...
495845,25326475,2025-12-30 21:15:00,DISABLED VEHICLE,Resolved,0.0,1S23,nopn,0.0,0.0,Clear,0
495846,25326480,2025-12-30 21:25:00,TRAFFIC STOP,Warning,0.0,1S23,nopn,0.0,0.0,Clear,0
495847,25326519,2025-12-30 22:24:00,CHECK WELFARE,Assisted,420.0,3J81,nopn,0.0,0.0,Clear,1
495848,25326528,2025-12-30 22:34:00,AUDIBLE ALARM,False Alarm,600.0,1S21,nopn,0.0,0.0,Clear,0
495849,25326529,2025-12-30 22:39:00,DISPUTE,Assisted,420.0,1S13,nopn,0.0,0.0,Clear,0

In [43]:
MCSLC_Data

,City,ID,Call Time,Nature,Nature #2,Nature #3,Nature #4,Nature #5,Closed As,Seconds to Arrival,Precipitation Type,Snow,Snow Depth,Conditions
0,Eugene,12485,2024-08-18 14:12:00,Substance use,NaN,NaN,NaN,NaN,Remained in community,1320.0,nopn,0.0,0.0,Partially cloudy
1,Springfield,12487,2024-08-18 15:35:00,Suicidality or suicide attempt,NaN,NaN,NaN,NaN,Remained in community,3000.0,nopn,0.0,0.0,Partially cloudy
2,Eugene,12290,2024-08-18 19:43:00,Needing social/mental health services,Suicidality or suicide attempt,NaN,NaN,NaN,Remained in community,2220.0,nopn,0.0,0.0,Partially cloudy
3,Eugene,12354,2024-08-19 16:29:00,Harm/risk of harm to self/others/property,Needing social/mental health services,NaN,NaN,NaN,Remained in community,1620.0,nopn,0.0,0.0,Partially cloudy
4,Eugene,12435,2024-08-19 16:29:00,Other,NaN,NaN,NaN,NaN,Remained in community,120.0,nopn,0.0,0.0,Partially cloudy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3510,Eugene,14107,2025-12-16 21:47:00,Suicidality or suicide attempt,NaN,NaN,NaN,NaN,Emergency Department,600.0,rain,0.0,0.0,Rain - Partially Cloudy
3511,Eugene,13731,2025-12-16 23:30:00,Harm/risk of harm to self/others/property,Difficulty functioning,Paranoia,NaN,NaN,Emergency Department,1680.0,rain,0.0,0.0,Rain - Partially Cloudy
3512,Eugene,13790,2025-12-17 01:33:00,Agitation or disruptive behavior,Paranoia,NaN,NaN,NaN,Remained in community,1980.0,rain,0.0,0.0,Rain - Partially Cloudy
3513,Eugene,12698,2025-12-17 02:45:00,Difficulty functioning,NaN,NaN,NaN,NaN,Remained in community,1560.0,rain,0.0,0.0,Rain - Partially Cloudy
3514,Springfield,13209,2025-12-17 02:57:00,Agitation or disruptive behavior,Difficulty functioning,NaN,NaN,NaN,Remained in community,2460.0,rain,0.0,0.0,Rain - Partially Cloudy

# Snow Threshold Filtering

In [45]:
# Get rid of any row where "Precipitation Type" is Snow but "Snow Depth" isn't greater than 0.0.
CAD_Data = CAD_Data[~((CAD_Data["Precipitation Type"] == "Snow") & (CAD_Data["Snow Depth"] <= 0.0))]
SPD_Data = SPD_Data[~((SPD_Data["Precipitation Type"] == "Snow") & (SPD_Data["Snow Depth"] <= 0.0))]
MCSLC_Data = MCSLC_Data[~((MCSLC_Data["Precipitation Type"] == "Snow") & (MCSLC_Data["Snow Depth"] <= 0.0))]

# Split Data for Each Organization by Weather

In [49]:
# Split data for each dataset based on Precipitation type is nopn, rain, or snow.
CAD_Data_NoPrecip = CAD_Data[CAD_Data["Precipitation Type"] == "nopn"]
CAD_Data_Rain = CAD_Data[CAD_Data["Precipitation Type"] == "rain"]
CAD_Data_Snow = CAD_Data[CAD_Data["Precipitation Type"] == "snow"]

SPD_Data_NoPrecip = SPD_Data[SPD_Data["Precipitation Type"] == "nopn"]
SPD_Data_Rain = SPD_Data[SPD_Data["Precipitation Type"] == "rain"]
SPD_Data_Snow = SPD_Data[SPD_Data["Precipitation Type"] == "snow"]

MCSLC_Data_NoPrecip = MCSLC_Data[MCSLC_Data["Precipitation Type"] == "nopn"]
MCSLC_Data_Rain = MCSLC_Data[MCSLC_Data["Precipitation Type"] == "rain"]
MCSLC_Data_Snow = MCSLC_Data[MCSLC_Data["Precipitation Type"] == "snow"]

# Later Steps to be Completed Later This Week.